version: '3'
services:
  db:
    image: "postgres:10.3"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  db:
